title: Towards a Computational Literary Science
description: An interdisciplinary research project on distant reading approaches for English literature
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
